### ISSUE TITLE
CRAN Check Failure for Upcoming broom Release

### ISSUE THREAD

**Issue by simonpcouch** [alexpkeil1/qgcomp#12]
Hi there! The broom dev team just ran reverse dependency checks on the upcoming broom 0.7.0 release and found new NOTEs for the CRAN version of this package. I've pasted the results below, which seem to result from our decision to no longer export the `finish_glance()` function in favor of adding more specific calls to `stats::BIC()` et al. (see [this issue](https://github.com/tidymodels/broom/pull/597)).

*   checking dependencies in R code ... NOTE
    ```
    Missing or unexported object: ‘broom::finish_glance’
    ```

We hope to submit this new version of the package to CRAN in the coming weeks. If you encounter any problems fixing these issues, please feel free to reach out!🙂

**Comment by alexpkeil1** [comment]
Fixed in v 2.4.0
