### ISSUE TITLE
How to interpret the results of non-linearity ?

### ISSUE THREAD

**Issue by LeungJun24** [alexpkeil1/qgcomp#17]
When we conduct an non-linear terms using qgcomp.boot. How to interpret the results of non-linearity ? What’s the means of the p vaule of psi1 and psi2, respectively.
![360截图20210427224454465](https://user-images.githubusercontent.com/65936988/116261528-5064e300-a7aa-11eb-9aea-3a07cd81b7ea.jpg)
![360截图20210427225837518](https://user-images.githubusercontent.com/65936988/116263706-2a404280-a7ac-11eb-9d6d-5701ad375b89.jpg)

**Comment by alexpkeil1** [comment]
Good question - this isn't explained well enough in the vignette! I'll work on some text for that and update the next time I have a few minutes.

Meanwhile, the interpretation is rather simple if you make an analogy to a linear model. In a usual linear model with one continuous exposure X and one continuous outcome Y, one way of exploring non-linearity is to fit a linear model with quadratic terms like:

y_i  = b0 + b1*X_i + b2*X_i^2 + e_i

with individual observations denoted by "_i" and the error term  = e_i, and model parameters b0 (intercept) b1 ("main effect" for X) and b2 (quadratic term for X). Here, you would interpret b1 as the linear part of the regression line and b2 as the quadratic part of the regression line. These are difficult to interpret independently, but a test of b2 is a rough test of non-linearity. 

For qgcomp, you can substitute in "the mixture" for X. In that case psi1 is the linear part of the overall curve and psi2 is the quadratic part. Thus, a test of psi2 is a rough test of non-linearity of the effect of increasing all exposures simultaneously. If psi2 is positive (and the outcome is bad), this is roughly interpreted as meaning that a 1 quantile increase of all exposures is worse for you if you are already highly exposed, relative to if you had a low exposure.

**Comment by alexpkeil1** [comment]
Text is updated in vignette in v2.8.0 on CRAN
