### ISSUE TITLE
WISH: URL and BugReports

### ISSUE THREAD

**Issue by HenrikBengtsson** [alexpkeil1/qgcomp#21]
Please consider adding URL and BugReports fields to this package DESCRIPTION file so that it is easy to find this repo from https://cran.r-project.org/package=qgcomp.

**Comment by alexpkeil1** [comment]
Great idea. This will be implemented in the next release.

**Comment by alexpkeil1** [comment]
Implemented in: https://github.com/alexpkeil1/qgcomp/commit/2b414e1b7dfecd9afd67e9bc410b3b8106fbfc4f
