### ISSUE TITLE
future::plan(): better approach + don't use 'transparent'

### ISSUE THREAD

**Issue by HenrikBengtsson** [alexpkeil1/qgcomp#22]
Hi,

I see that you use for instance:

https://github.com/alexpkeil1/qgcomp/blob/95e0b74adecb8554f1208ecedbc1f97c0acf6141/R/base_surv.R#L626-L632

Please use the following instead:

```
if (parplan) {
  oplan <- future::plan(strategy = future::multisession)
  on.exit(plan(oplan), add = TRUE)
}
```

This is the proper way to do it, cf. `help("plan", package = "future")`.  It also avoids using `transparent`, which should not be used in package code and will eventually be deprecated.

**Comment by alexpkeil1** [comment]
Fixed in https://github.com/alexpkeil1/qgcomp/commit/5519045093b88438f9a8baa7ab5f00e8e60a704f

**Comment by HenrikBengtsson** [comment]
FYI, `transparent` is also used in the vignette, cf. https://github.com/alexpkeil1/qgcomp/search?q=transparent

**Comment by alexpkeil1** [comment]
Fixed in https://github.com/alexpkeil1/qgcomp/commit/e742d511aef10514c48568bfa0fe84a44712149b
