### ISSUE TITLE
adjusting survival plot yaxis

### ISSUE THREAD

**Issue by sethfrnd** [alexpkeil1/qgcomp#24]
I have been attempting to adjust the yaxis using ylim as in a ggplot2 object, but I have been unsuccessful. Any suggestions?

**Comment by alexpkeil1** [comment]
Try this (ylim is dangerous as a general tool because it can truncate the data):
```
library(qgcomp)
library(ggplot2)
set.seed(50)
N=200
dat <- data.frame(time=(tmg <- pmin(.1,rweibull(N, 10, 0.1))), 
                  d=1.0*(tmg<0.1), x1=runif(N), x2=runif(N), z=runif(N))
expnms=paste0("x", 1:2)
f = survival::Surv(time, d)~x1 + x2
(obj <- qgcomp.cox.boot(f, expnms = expnms, data = dat, B=10, MCsize=2000))

p = plot(obj, suppressprint = TRUE)
p + coord_cartesian(ylim=c(.5, 1))
```

**Comment by sethfrnd** [comment]
This works great! Thank you! The code works on my home computer. Unfortunately, it doesn't seem to work on the remote desktop I'm using. 
p returns as NULL
Must be an issue with the remote desktop.

**Comment by alexpkeil1** [comment]
Closing this with additional suggestion to save the plot (p object) to file on remote. ggsave() or png() may both work, depending on graphics environment, but how your remote desktop handles printing ggplot2 objects is beyond scope here. Let me know if this is a unique issue to the package though (i.e. do you have the same issue with standard ggplot2 objects that you save?), and I can search for more systematic fixes in the underlying qgcomp::plot code.

**Comment by alexpkeil1** [comment]
Did you try saving it with ggsave?
