### ISSUE TITLE
plot when covariate is factor produces error

### ISSUE THREAD

**Issue by sethfrnd** [alexpkeil1/qgcomp#25]
When I use factor(gender) in my R model with survival::Surv() and then use plot() to plot my bootstrapped survival curve I obtained using qgcomp.cox.boot I get the error: object 'gender' not found. 

However, when I convert gender to a numeric variable it runs fine. 

This is more complicated when I have a multi-class variable like race. I can't convert that to an ordinal variable. How do I get around this to plot the survival curves?

Thank you!!

**Comment by alexpkeil1** [comment]
This is a bug related to some ugly scoping issues in the survival package. I may be able to put a kludge into the package code to work around this. In the meantime, you can fix this issue by creating explicit indicator variables as numeric variables. Here's an example 
```
library(qgcomp)
library(ggplot2)
set.seed(50)
N=200
dat <- data.frame(time=(tmg <- pmin(.1,rweibull(N, 10, 0.1))), 
                  d=1.0*(tmg<0.1), x1=runif(N), x2=runif(N), z=factor(sample(c(1:3), N, replace=TRUE)))
expnms=paste0("x", 1:2)
f = survival::Surv(time, d)~x1 + x2 + z

# example 1: showing the error with a factor variable
(obj <- qgcomp.cox.boot(f, expnms = expnms, data = dat, B=10, MCsize=2000))
names(coef(obj$fit))
# "x1" "x2" "z2" "z3"


# not run
#p = plot(obj) # gives error
# Error in eval(predvars, data, env) : object 'z' not found



# example 2: workaround for factor variables
# create explicit indicator variables
dat$z2 = as.numeric(dat$z==2)
dat$z3 = as.numeric(dat$z==3)
f = survival::Surv(time, d)~x1 + x2 + z2 + z3
(obj2 <- qgcomp.cox.boot(f, expnms = expnms, data = dat, B=10, MCsize=2000))
names(coef(obj2$fit))
# [1] "x1" "x2" "z2" "z3"
all(coef(obj$fit) == coef(obj2$fit)) # TRUE: identical underlying fits, psi estimates may differ at smaller MCsize values
plot(obj2) # no error
```

**Comment by sethfrnd** [comment]
I see! So essentially creating dummy variables! Fantastic. Thank you so much for your help!
