### ISSUE TITLE
Fitting a competing risks model

### ISSUE THREAD

**Issue by sethfrnd** [alexpkeil1/qgcomp#29]
This isn't a "bug" just a question of how estimating a competing risks model might be accomplished. 

It seems that the Surv package in R doesn't do competing risks. For that, you have to use the cmprsk package. BUT then qgcomp can’t estimate a model created from cmprsk...

Is there a way around this?

Thank you for your help.

**Comment by alexpkeil1** [comment]
Not sure I understand you’re after or what the concern is about the standard functionality. The survival package fits Cox models, multi state models, and a Fine-Gray model. All of those consider competing risks in various ways. That said, I’m not sure whether anything other than the standard Cox model plays nicely with qgcomp functions. I would love to hear back if you test the other approaches!On Mar 22, 2023, at 9:36 AM, sethfrnd ***@***.***> wrote:﻿
This isn't a "bug" just a question of how estimating a competing risks model might be accomplished.
It seems that the Surv package in R doesn't do competing risks. For that, you have to use the cmprsk package. BUT then qgcomp can’t estimate a model created from cmprsk...
Is there a way around this?
Thank you for your help.

**Comment by sethfrnd** [comment]
I think my issue is really about fitting a Fine-Gray model with complex survey data and THEN applying it to qgcomp. I'm a bit ahead of myself. I'm closing this because I have to figure out those early steps first.

**Comment by alexpkeil1** [comment]
Feel free to keep this open as an enhancement if the other approaches  don’t work out of the box. It’s a good idea to bring in other approaches to competing risks aside from the Cox model!On Mar 22, 2023, at 3:02 PM, sethfrnd ***@***.***> wrote:﻿
Closed #29 as completed.
