### ISSUE TITLE
quasipoisson distribution of data: how to do

### ISSUE THREAD

**Issue by ZiqingTTang** [alexpkeil1/qgcomp#31]
> m4<-qgcomp.noboot(death~as.factor(city)+as.factor(year)+
tmean.win+tmean.sum+ tsd.sum+tsd.win+no2+co+so2+03+offset(Logpop),
expnms=comp, data=data, q=20, family=quasipoisson())

when I add", family=quasipoisson()",one error exist:

Error in print.qgcompfitCxD : object "testtype" not found
In addition: Warning message:In print.agcompfit(x) :
The quasipoisson distribution has not been tested with agcomp! Please use with extreme caution and check results thoroughly with simulated data to ensure it works.

**Comment by ZiqingTTang** [comment]
Recently studying qgcomp, can you give me some help or tips? My data is continuous variable, and the data distribution is conditional Poisson distribution，How to solve this problem

**Comment by alexpkeil1** [comment]
I submitted a bug fix for this. Try installing the dev version of the package (instructions: https://github.com/alexpkeil1/qgcomp/issues/11), and see if this fixes the problem. I haven't tested this GLM family, so I can't guarantee that it works, but it should clear up that error at least. I haven't had any problems with other families, so I don't anticipate that there will be issues, but I just want to be sure you know it hasn't gone through thorough testing.

**Comment by alexpkeil1** [comment]
> Recently studying qgcomp, can you give me some help or tips? My data is continuous variable, and the data distribution is conditional Poisson distribution，How to solve this problem

I can't advise on specifics of your analysis. I would generally say that the family you would normally choose for a GLM with a single exposure is the family you should choose for qgcomp.

**Comment by ZiqingTTang** [comment]
Thanks a lot for your reply and help, and I have also learned useful information from it

**Comment by alexpkeil1** [comment]
Fixed in newest release on CRAN (v2.15.2)
