### ISSUE TITLE
nhanes weight

### ISSUE THREAD

**Issue by nkchangshu** [alexpkeil1/qgcomp#32]
How should the NHANES weight be handled in the fitting of the qgcomp model? Is there an appropriate parameter that can be used?

**Comment by alexpkeil1** [comment]
There is a "weights" parameter that can be used much like the weight argument in glm. You may need to use the bootstrapped version to get appropriate standard errors.

e.g. see documentation: https://rdrr.io/cran/qgcomp/man/qgcomp.glm.noboot.html
