### ISSUE TITLE
id (sample cluster) when a lonely PSU

### ISSUE THREAD

**Issue by sethfrnd** [alexpkeil1/qgcomp#33]
Just trying to understand the default qgcomp is using when there is a lonely PSU. From what I understand the options can be:
1. Assigning that participant to another PSU (done by the user)
2. Centering the lonely PSU around the sample grand mean
3. Make no contribution to the variance

I know that I have a lonely PSU, but qgcomp.cox.noboot and qgcomp.cox.boot run without a warning despite the lonely PSU. So there must be a default way of handling it. Maybe there is something I'm missing? Just want to know what the default is so I can clarify for reviewers.

Thanks!

**Comment by alexpkeil1** [comment]
I don't know what a PSU is. A working example would help here.

**Comment by sethfrnd** [comment]
Sorry for the lack of clarity. PSU is "Primary Sampling Unit". Usually refers to sample clustering in the case of a clustered sample design. So people clustered within census tract for example.

**Comment by alexpkeil1** [comment]
Got it. The cluster bootstrapping in the qgcomp.cox.boot will do a conditional sampling procedure in which the clusters are sampled at random, but individuals within a cluster are not. This scheme has been shown to mimic a GEE, in that no parametric distribution is assumed for correlation of outcomes within a sampling unit (i.e. it's not like a random intercept model). In your case, that single PSU will either be sampled, or not, in a given bootstrap iteration, which correctly gives no error. If you do have clustering, then using the bootstrapped version is more appropriate (unless you use the cluster argument, which gets passed to coxph: https://stats.stackexchange.com/questions/178944/precisely-how-does-rs-coxph-handle-repeated-measures). 

Section 8 of the vignette explains some of this outside of the Cox model, if you haven't seen it.

Somewhat confusingly, to use clustering in the bootstrapped version, you have to use the "id" parameter, and to use clustering in the non-boostrapped version, you have to use "cluster(<variable name>)" in the model formula like:

```
qgcomp.cox.noboot(survival::Surv(time, d)~x1 + x2 + cluster(id), expnms = expnms, data = dat)
```

That approach is essentially a GEE and you get a cluster-robust variance estimator that doesn't assume multiple observations per cluster.

This is confusing, so I'll try to note it in the documentation and make it a little more unified.
