### ISSUE TITLE
Plot issues with "noboot" functions

### ISSUE THREAD

**Issue by alexpkeil1** [alexpkeil1/qgcomp#34]
There is a bug in ggplot2 code that prevents qgcomp plots (bar plots with weights) from printing correctly under some pretty specific circumstances (e.g. bars on one side of the plot are much wider than the bars on the other side of the plot).

I can't fix this on my end, but will update this issue once I have a chance to put in a bug report for ggplot2.

There are currently no fixes other than plotting the weights manually, but I can't provide a general solution to that.

Below is a reproducible example that uses some of the underlying qgcomp plotting code, which is just a wrapper around ggplot2 functions:

```
library(ggplot2)

pw = c(x1=.9, x3=0.1)
nw = c(x2=0.5, z=0.5)
nms = names(sort(c(pw,nw)))

ggplot() + 
  stat_identity(aes(x=v, y=w), position = "identity", geom="bar", 
                data=data.frame(w=pw, v=names(pw))) + 
  scale_x_discrete(name="Variable", limits=nms, breaks=nms, labels=nms, drop=FALSE) 
ggplot() + 
  stat_identity(aes(x=v, y=w), position = "identity", geom="bar", 
                data=data.frame(w=nw, v=names(nw))) + 
  scale_x_discrete(name="Variable", limits=nms, breaks=nms, labels=nms, drop=FALSE)
```

**Comment by kestlermai** [comment]
Hey, alexpkeil1
This seems to have found a solution: define the width of bars.
`  stat_identity(aes(x=v, y=w), position = "identity", geom="bar", width = 0.8,
                data=data.frame(w=neg.weights, v=names(neg.weights)),
                fill=gray(1-poscolwt)) +`

![qgcomp-test](https://github.com/alexpkeil1/qgcomp/assets/105265970/b534a930-d14d-42ba-bb24-c717391fbc75)

**Comment by alexpkeil1** [comment]
@kestlermai has a nice solution. 

It also appears that ggplot2 was updated, so try updating ggplot2 if you are seeing this issue. The following minimal example now works in ggplot2 v3.5.0:

```
library(ggplot2)

pw = c(x1=.9, x3=0.1)
nw = c(x2=0.5, z=0.5)
nms = names(sort(c(pw,nw)))

ggplot() + 
  stat_identity(aes(x=v, y=w), position = "identity", geom="bar", 
                data=data.frame(w=c(pw,-nw), v=c(names(pw), names(nw)))) + coord_flip()
```
