### ISSUE TITLE
negative weight

### ISSUE THREAD

**Issue by lifeng-zhu** [alexpkeil1/qgcomp#35]
Excuse me. I am studying the association between particulate matter components (Organic matter, black carbon, sulfate, nitrate, ammonium) and death, although all five components increase the risk of death in  single pollutant model, however, when I use joint exposure with qgcomp, two pollutants (sulfate, nitrate) have negative weights. I am very difficult to interpret it.

**Comment by alexpkeil1** [comment]
This isn't an issue with the package or a bug. 

Your are seeing the impact of adjustment for other pollutants. The weights will be negative even if the individual coefficients are very, very tiny, which you could easily see if those pollutants have null effects but are still confounded by other pollutants.

**Comment by lifeng-zhu** [comment]
Thank you very much, this helps me a lot!
