### ISSUE TITLE
interpreting results from modelbound.boot

### ISSUE THREAD

**Issue by ndsubison2178** [alexpkeil1/qgcomp#36]
My outcome is binary and I fitting a model using **qgcomp.boot**, rr = TRUE, B=5000, q=4

The summary estimates from qgcomp.boot shows 

                                Estimate           Std.Error
             Intercept         -4.109              0.3428
            psi1               **0.06719**        0.1635

The summary from modelbound.boot(...) shows

                           quantile      midpoint         linepred         r
                   0      0                 0.125             -4.109        **0.0456**
                   1      1                 0.375                               
                   2      2                 0.625
                   3      3                 0.875

the vignette https://cran.r-project.org/web/packages/qgcomp/qgcomp.pdf, pg 14 says the model estimate of the regression line E(Y|X) are expected to include the true value of E(Y|X) in 95% of studies. My y is 1 or 0, how does the estimate r= **0.0456** translate to  E(Y|X) for my binary outcome ? Please help. Thanks.

**Comment by alexpkeil1** [comment]
Hi,
The conditional expected value (E(Y|X)) of a binary variable is just the mean of Y, given X. The mean of a binary outcome coded as 0/1 will necessarily be between zero and one. This isn't an issue with the package but with interpretation of epidemiologic results, so I am closing this issue.
