### ISSUE TITLE
Interpretation of results

### ISSUE THREAD

**Issue by beyound88** [alexpkeil1/qgcomp#37]
Hi！ I'm looking for advice on how to interpret the results of qgcomp.boot. I am using multivariate logistic regression and x1,x2,x3 are all negatively correlated with Y. In qgcomp.boot analysis (adjusted for the same variables) I noticed that the weight value of x1 is negative and the effect sizes are in a different order than in the logistic regression analysis, how should I interpret the anomalous results? Is using WQS a better option? How can I understand the weight values?

**Comment by alexpkeil1** [comment]
There are no weights in the qgcomp.boot methods, so I'm not sure what you
mean here. Bivariate correlations are not the same as adjusted regression
results, so you may see associations in different directions as a result of
confounding. I can't offer much other advice without any specifics.

**Comment by beyound88** [comment]
Hello, thank you for your reply, and please forgive me for the error in expression! I am using qgcomp.noboot. How can I understand the weight values?  How should I properly interpret the results of the weights? I don't quite understand what the positive and negative represent? Is it just positive and negative correlation? What about contradictions with positive or negative correlations derived from traditional regression analyses? Sorry, I am in the initial learning stage and would be grateful if you could respond!



Best wishes!










| |
青年
|
|
***@***.***
|
---- Replied Message ----
| From | Alex ***@***.***> |
| Date | 7/22/2024 01:28 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [alexpkeil1/qgcomp] Interpretation of results (Issue #37) |
There are no weights in the qgcomp.boot methods, so I'm not sure what you
mean here. Bivariate correlations are not the same as adjusted regression
results, so you may see associations in different directions as a result of
confounding. I can't offer much other advice without any specifics.

**Comment by alexpkeil1** [comment]
Please read the package vignette in R and let me know if you have any questions after that. Example 3 might be most relevant.

From: beyound88 ***@***.***>
Date: Wednesday, July 24, 2024 at 1:57 AM
To: alexpkeil1/qgcomp ***@***.***>
Cc: Alex Keil ***@***.***>, Comment ***@***.***>
Subject: Re: [alexpkeil1/qgcomp] Interpretation of results (Issue #37)
Hello, thank you for your reply, and please forgive me for the error in expression! I am using qgcomp.noboot. How can I understand the weight values? How should I properly interpret the results of the weights? I don't quite understand what the positive and negative represent? Is it just positive and negative correlation? What about contradictions with positive or negative correlations derived from traditional regression analyses? Sorry, I am in the initial learning stage and would be grateful if you could respond!



Best wishes!










| |
青年
|
|
***@***.***
|
---- Replied Message ----
| From | Alex ***@***.***> |
| Date | 7/22/2024 01:28 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [alexpkeil1/qgcomp] Interpretation of results (Issue #37) |
There are no weights in the qgcomp.boot methods, so I'm not sure what you
mean here. Bivariate correlations are not the same as adjusted regression
results, so you may see associations in different directions as a result of
confounding. I can't offer much other advice without any specifics.

**Comment by beyound88** [comment]
Thank you very much for your help!
