### ISSUE TITLE
Extract the overall metal exposure value that represents all metal exposure concentrations

### ISSUE THREAD

**Issue by zhonghua723** [alexpkeil1/qgcomp#39]
Can we extract an overall metal exposure value that represents all metal exposure concentrations? This is useful to estimate the association between overall metal exposure with other indexes!

**Comment by alexpkeil1** [comment]
That capability is not available via qgcomp.

From: zhonghua723 ***@***.***>
Date: Wednesday, September 18, 2024 at 3:32 AM
To: alexpkeil1/qgcomp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [alexpkeil1/qgcomp] Extract the overall metal exposure value that represents all metal exposure concentrations (Issue #39)

Can we extract an overall metal exposure value that represents all metal exposure concentrations? This is useful to estimate the association between overall metal exposure with other indexes!

**Comment by alexpkeil1** [comment]
Duplicate question: https://github.com/alexpkeil1/qgcomp/issues/38
