### ISSUE TITLE
qgcomp.cox.boot can not fit time-varying exposures

### ISSUE THREAD

**Issue by ShiHongjing** [alexpkeil1/qgcomp#41]
My study focuses on multiple air pollutants and a certain health outcome. For the air pollutant concentrations I chose time-varying concentrations, i.e. one assignment for each individual for 2010-2011, another for 2011-2012, and so on, and there may be multiple records for each individual, but there is no overlap in time between them. The model is as follows： 
formula = as.formula(paste0("Surv(tstart, tstop, end)", "~", "pm25_vary1_1 + pm10_vary1_1 + o3_vary1_1 + no2_vary1_1", "+", adj))
fit<-qgcomp.cox.boot(formula, data = agetest, expnms = xnm, q = 4, B = 10, MCsize = 1000)

there is no "id" information in agetest, but following error occurs：
1: In FUN(X[[i]], ...) :
  Late entry/counting process style data is detected 
              in call to qgcomp.cox.boot. Note:
              this function is not valid with time varying
              exposures/covariates in the model if using counting process
              style data (>1 record per individual).

**Comment by alexpkeil1** [comment]
Hi. Do you have a question about this? It looks as though you have all covariates entered linearly, in which case you do not need to use the bootstrapped version to obtain parameter estimates. See here for an example: https://gist.github.com/alexpkeil1/69c3d30e35e2b9732ca9d549c3f7a494

Unfortunately, if you needed the bootstrapped version for some reason, it is not implemented for time-varying exposures per the message. Currently, there are no plans to change this.
