### ISSUE TITLE
Inquiry about the qgcomp.cox.noboot() function

### ISSUE THREAD

**Issue by senmingjiu** [alexpkeil1/qgcomp#43]
Hello!
I encountered some issues when using the qgcomp.cox.noboot() function, and I hope to get your help.
I used this function to build a model with the following code:

> basurv <- Surv(time = data[["A1_years"]], event = data[["A1_y"]])
> FML <- as.formula(paste0('basurv~ WholeGrains_Cat + TSVegetables_Cat+  
+   Vegetables_Cat +Fruits_Cat + DairyFood_Cat +  ReaMeat_Cat + Poultry_Cat + 
+   Eggs_Cat + Fish_Cat + DryBeans_Cat + SoyFood_Cat + Nuts_Cat + Fats_Cat +Sugar_Cat +
+                          Age+Sex+Ethnic_cat+TDI+YearsEducation+BMI'))
> qgcomp_model <- qgcomp.cox.noboot(
+   FML,
+   expnms = c("WholeGrains_Cat", "TSVegetables_Cat",  "Vegetables_Cat", "Fruits_Cat", "DairyFood_Cat",  
+              "ReaMeat_Cat", "Poultry_Cat", "Eggs_Cat", "Fish_Cat", "DryBeans_Cat",   
+              "SoyFood_Cat", "Nuts_Cat", "Fats_Cat", "Sugar_Cat"),
+   data = data,
+   q=4,
+   id=data[["eid"]])
> qgcomp_model

Among these variables, "WholeGrains_Cat" and other related variables are binary variables (I have already set them as numeric 0 and 1). After running the code, the result is:

Scaled effect size (positive direction, sum of positive coefficients = 0)
None

Scaled effect size (negative direction, sum of negative coefficients = 0)
None

Mixture log(hazard ratio) (Delta method CI):

     Estimate Std. Error Lower CI Upper CI Z value Pr(>|z|)
psi1       NA          0       NA       NA      NA       NA

It seems that the proportion of each component has not been calculated. What I would like to ask is, is the qgcomp.cox.noboot() function only applicable to continuous variable exposures? Is it unable to handle numeric binary variables like the 0 - 1 ones I have?
Thank you very much for your time and assistance!

**Comment by alexpkeil1** [comment]
Hi,
If they are all binary, then you can set q=NULL and you get the joint effect of changing all of the exposures from 0 to 1. If they are not all binary, then I don't think the model is interpretable.
